"""Batteries-optional microservice runtime.

One ``Host``, many ``Entrypoint``s. Describe a service once as an ``AppSpec`` and
run it through any number of pluggable entrypoints (HTTP, gRPC, scheduler,
consumer, daemon, one-shot) under one unified lifecycle.
"""

from __future__ import annotations

from .__version__ import __version__
from .adapters.builtin import DaemonEntrypoint, OneShotEntrypoint
from .core import (
    DEFAULT_CLEANUP_TIMEOUT_SECONDS,
    DEFAULT_DRAIN_GRACE_SECONDS,
    STANDARD_PROPAGATION_HEADERS,
    AppScopeProtocol,
    AppSpec,
    AsyncWarmer,
    BaseServiceSettingsProtocol,
    BootstrapContext,
    ChainRedactor,
    CleanupTimeoutError,
    ContextSetter,
    DependencyContainerProtocol,
    DrainTimeoutError,
    ErrorInfo,
    ErrorKind,
    ErrorTrackingSettingsProtocol,
    HealthCheckerProtocol,
    HealthRegistry,
    HealthReport,
    Host,
    HttpErrorRendererProtocol,
    KafkaProducerWarmupError,
    KeyRedactor,
    Lifecycle,
    LifecycleHookProtocol,
    LoggingSettingsProtocol,
    MetricsSettingsProtocol,
    ObsConfig,
    ObservabilityManager,
    ObsSetupContext,
    PostgresWarmupError,
    ProbeStatus,
    ProblemDetailsRenderer,
    RedisWarmupError,
    RenderedError,
    Service,
    ServiceContext,
    ServiceError,
    ServiceWrightError,
    TracingSettingsProtocol,
    UnitScopeProtocol,
    ValueRedactor,
    WarmupError,
    WarmupTimeoutError,
    bind_context,
    bind_context_values,
    collect_warmers,
    current_context,
    event_loop_factory,
    get_context_value,
    is_safe_context_id,
    mask_private_error,
    perform_warmup,
    propagation_metadata,
    register_sink,
    run,
    run_sync,
    set_context_value,
    warmup_async,
)
from .core.contracts import Entrypoint, Plugin, ScopedEntrypoint, ServerEntrypoint

__all__ = [
    "DEFAULT_CLEANUP_TIMEOUT_SECONDS",
    "DEFAULT_DRAIN_GRACE_SECONDS",
    "STANDARD_PROPAGATION_HEADERS",
    "AppScopeProtocol",
    "AppSpec",
    "AsyncWarmer",
    "BaseServiceSettingsProtocol",
    "BootstrapContext",
    "ChainRedactor",
    "CleanupTimeoutError",
    "ContextSetter",
    "DaemonEntrypoint",
    "DependencyContainerProtocol",
    "DrainTimeoutError",
    "Entrypoint",
    "ErrorInfo",
    "ErrorKind",
    "ErrorTrackingSettingsProtocol",
    "HealthCheckerProtocol",
    "HealthRegistry",
    "HealthReport",
    "Host",
    "HttpErrorRendererProtocol",
    "KafkaProducerWarmupError",
    "KeyRedactor",
    "Lifecycle",
    "LifecycleHookProtocol",
    "LoggingSettingsProtocol",
    "MetricsSettingsProtocol",
    "ObsConfig",
    "ObsSetupContext",
    "ObservabilityManager",
    "OneShotEntrypoint",
    "Plugin",
    "PostgresWarmupError",
    "ProbeStatus",
    "ProblemDetailsRenderer",
    "RedisWarmupError",
    "RenderedError",
    "ScopedEntrypoint",
    "ServerEntrypoint",
    "Service",
    "ServiceContext",
    "ServiceError",
    "ServiceWrightError",
    "TracingSettingsProtocol",
    "UnitScopeProtocol",
    "ValueRedactor",
    "WarmupError",
    "WarmupTimeoutError",
    "__version__",
    "bind_context",
    "bind_context_values",
    "collect_warmers",
    "current_context",
    "event_loop_factory",
    "get_context_value",
    "is_safe_context_id",
    "mask_private_error",
    "perform_warmup",
    "propagation_metadata",
    "register_sink",
    "run",
    "run_sync",
    "set_context_value",
    "warmup_async",
]
