"""Shared constants for microservice runtimes."""

DEFAULT_CLEANUP_TIMEOUT_SECONDS = 10.0
DEFAULT_METRICS_SHUTDOWN_TIMEOUT_SECONDS = 5.0
DEFAULT_WARMUP_TIMEOUT_SECONDS = 60.0
DEFAULT_DRAIN_GRACE_SECONDS = 30.0
DEFAULT_DRAIN_TIMEOUT_BUFFER_SECONDS = 5.0
